spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compass_deyvid?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
